export const SET_USER = 'SET_USER';
export const SIGN_OUT = 'SIGN_OUT';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const NEED_VERIFICATION = 'NEED_VERIFICATION';
export const SET_SUCCESS = 'SET_SUCCESS';

//
export const SET_QUESTIONS = 'SET_QUESTIONS';
export const SET_FETCH_QUESTIONS_LOADING = 'SET_FETCH_QUESTIONS_LOADING';
export const SET_FETCH_QUESTIONS_ERROR = 'SET_FETCH_QUESTIONS_ERROR';
export const SET_CURRENT_QUESTION_ID = 'SET_CURRENT_QUESTION_ID';
