export const SET_USER = 'SET_USER';
export const SIGN_OUT = 'SIGN_OUT';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const NEED_VERIFICATION = 'NEED_VERIFICATION';
export const SET_SUCCESS = 'SET_SUCCESS';

//
export const GET_QUESTIONS = 'GET_QUESTIONS';
export const SET_QUESTIONS_LOADING = 'SET_QUESTIONS_LOADING';
export const SET_QUESTIONS_ERROR = "SET_QUESTIONS_ERROR";

export const GET_USER_ANSWERS = 'GET_USER_ANSWERS';
export const SUBMIT_ANSWER = 'SUBMIT_ANSWER';
